feat: Implemented AdapterInterface and Models
CESNET/proxyaai_perun_connection_manager pull request #1
Opened 2022-02-02 13:34 UTC by PeterBolha

2022-02-02 17:57 UTC, vyskocilpavel requested changes
The models look ok on the first look.

Some changes need to be done to the methods definitions(Some argument or return type is not correct).

2022-02-02 17:57 UTC, vyskocilpavel commented on Adapters/AdapterInterface.py
> +        raise NotImplementedError
entity_id should be string
uids should be [string]

2022-02-02 17:57 UTC, vyskocilpavel commented on Adapters/AdapterInterface.py
> +        raise NotImplementedError
entity_id should be string. The same is also in the other methods with the `entity_id` or similar parameter.

2022-02-02 17:57 UTC, vyskocilpavel commented on models/Member.py
> +        self.__status = status
__status should be checked that the value is one of the allowed states.

2022-02-02 17:57 UTC, vyskocilpavel commented on Adapters/AdapterInterface.py
> +        raise NotImplementedError
This comment is relevant also to the other methods of working or returning attributes.

`str` is not the correct return type for Attribute. Because the attribute can be of type: boolean, list, etc.
Maybe the new object (Attribute and maybe the AttributeValue) can be the better solution.

2022-02-03 08:53 UTC, xpavlic reviewed
Add to_string methods to model classes.

2022-02-03 08:53 UTC, xpavlic commented on models/HasIdInterface.py
> +class HasIdInterface(metaclass=abc.ABCMeta):
We can make it abstract class, and move id attribute and it's getter from subclasses.

2022-02-03 08:53 UTC, xpavlic commented on models/Member.py
> +        self.__status = status
I just add, that check shouldn't be case sensitive.

2022-02-03 11:05 UTC, melanger commented on Adapters/AdapterInterface.py
> +        raise NotImplementedError
By me, the argument `attributes` should be a list of strings and the return value should be a dictionary with string keys and mixed values.

2022-02-03 11:10 UTC, melanger commented on models/Group.py
> +    def get_id(self) -> int:
Have you considered using `__getter__` instead of typing out multiple methods?

2022-02-03 11:12 UTC, melanger commented on Adapters/AdapterInterface.py
> +        raise NotImplementedError
Therefore, I don't think we need both `get_*_attributes` and `get_*_attributes_values`, just one and return just the names and values in a dictionary (or set).

2022-02-03 11:15 UTC, melanger commented on Adapters/AdapterInterface.py
> +
A more Pythonic approach might be:
```suggestion
    def get_vo(self, short_name=None, id=None) -> Vo:
        """Get VO"""
        raise NotImplementedError
```
which might be implemented like this:
```
    def get_vo(self, short_name=None, id=None) -> Vo:
        if id and short_name:
            raise IllegalArgumentError
        if id:
            # find by ID
        elif short_name:
            # find by short name
        else:
            raise MissingArgumentError
```

2022-02-03 11:16 UTC, melanger commented on Adapters/AdapterInterface.py
> +    def get_facility_by_client_id(self, client_entity_id: int, entity_id_attr: str) -> Facility:
client ID is OIDC client ID, a string (there should be no `entity` here)

idp_entity_id and sp_entity_id are SAML entity IDs, also strings.

2022-02-03 11:20 UTC, vyskocilpavel commented on Adapters/AdapterInterface.py
> +    def get_facility_by_client_id(self, client_entity_id: int, entity_id_attr: str) -> Facility:
We can use `rp_identifier` as the correct argument name because we need only one method for getting facility by identifier.
The separate method for OIDC and for SAML is a relic from the past.

2022-02-03 11:26 UTC, melanger commented on Adapters/AdapterInterface.py
> +    def get_facility_attribute(self, facility: Facility, attr_name: str) -> str:
I wonder what the implementation and usage would look like.

Wouldn't it be easier if instead of passing a Facility object to this method, the Facility object would have a `__getter__` which calls this connector and passes only its ID? That's what is needed here anyway.

So something like:

```
class Facility:
    __getattr__(self, name):
        return connector.get_facility_attribute(self.id, name)

class AdapterInterface:
    # ...
    def get_facility_attribute(self, facility_id: int, attr_name: str) -> str
```

I guess that depends on the "big picture". I think we have multiple ways in the current implementations, and it would be great to unify the approach. Current approaches:
* entity object (e.g. Facility) carries only ID, connector/adapter methods accept integer ID, so the caller needs to call e.g. `facility->getId()` before using the connector/adapter
* entity object carries ID and some basic attributes, connector/adapter methods accept both integer ID or entity object, the connector/adapter calls `->getId()` if needed internally
* entity object carries all attributes (they are preloaded) so they can be accessed directly
* or the other way around - let entity object call the connector/adapter

Each way has its implications and some benefits. I would focus on making the use of the connector/adapter as easy as possible for the caller and choose the representation accordingly. I think the adapter/connector should hide as much complexity as possible and as many quirks of the RPC or LDAP as possible.

2022-02-03 11:28 UTC, melanger requested changes
See comments. At the very least entity_id and client_id attributes should be changed to strings.

2022-02-03 12:24 UTC, xpavlic commented on models/Group.py
> +    def get_id(self) -> int:
I have done some research about "private" in python. If you use a double leading underscore (e.g., __x), Python does a little obfuscation of the name. The property is still accessible from outside the class. It's not truly private. It's just kind of ... more opaque. I think, that model properties should not be underscored and should be accessible by dot notation without getters and setters. If we need anything specific, when gettting or setting property value (like some limits), we should use @property, which allows us still use dot notation.

2022-02-07 07:57 UTC, dBucik commented on models/Facility.py
> +        return self.__entity_id
Perhaps "entity_id" is not the best name, as the Facility in the context of ProxyIdP can represent both SAML and OIDC service (SAML -> entity_id, OIDC -> client_id). In general, I would call it "relying_party_id" instead, or just "rp_id".
Anyway, an even more, general question: do we need to store this? I would just point out that the Facility in general, does not need to represent SAML or OIDC service. @vyskocilpavel @melanger, what do you think, do we have some use case for non-RP Faciltiies?

2022-02-07 07:57 UTC, dBucik commented on Adapters/AdapterInterface.py
> +        raise NotImplementedError
In general, I would use "idp_id" instead. Imagine we will have OIDC IdPs :).

2022-02-07 08:07 UTC, melanger commented on models/Facility.py
> +        return self.__entity_id
> what do you think, do we have some use case for non-RP Faciltiies?

@dBucik I don't think so.

2022-02-07 13:33 UTC, PeterBolha commented on models/Group.py
> +    def get_id(self) -> int:
In my understanding, if we remove leadning underscores from properties, calling __getattr__ on property would amount to the same thing as calling class.property in case of these existing model attributes. @vyskocilpavel preferred using classic getters (and setters) to access properties for the sake of clarity so maybe it's up to further discussion. In case we remove leading underscores I think we could do without __getters__ altogether and use @property notation for input validation where needed.

2022-02-07 13:47 UTC, melanger commented on models/Group.py
> +    def get_id(self) -> int:
@vyskocilpavel Can you show a case where an explicit getter is clearer than using simple properties?

I know it is a standard in Java, but it's not the case in Python. IMHO explicit getters (without any extra code) are just more boilerplate.

2022-02-08 07:27 UTC, vyskocilpavel commented on models/Group.py
> +    def get_id(self) -> int:
@melanger I don't have any case where the explicit getter is clearer than using simple properties in this context.
But for example in the `Member` model, we need to check the value, which is set as `Status`, so I only mentioned that the standard convention(Not explicitly for Python) is using the same approach for the whole project.

And yes, my point of view is affected by using PHP and Java, so don't give so much to my opinion on what the Python code should look like.

2022-02-11 13:37 UTC, melanger requested changes

2022-02-11 13:37 UTC, melanger commented on Adapters/AdapterInterface.py
> +    def get_facility_attributes_values(
`get_facility_attributes_values` can be removed as well

2022-02-11 13:37 UTC, melanger commented on Adapters/AdapterInterface.py
> +    def get_vo_attributes(self, vo: Vo, attr_names: List[str]) -> dict[str, A]:
I think that all `get_..._attributes` methods should return a dictionary with string keys and mixed values (al Perun supported attribute types), which is probably `dict[str, Union[str, Optional[int], bool, List[str], dict[str, str]]]`

In your code, sometimes you have only `str`, here you have `A`.

2022-02-14 18:17 UTC, vyskocilpavel commented on Adapters/AdapterInterface.py
> +        raise NotImplementedError
This is a good point. We can add a new class `UserExtSource`.

Here is an example of the UserExtSource Object from PerunRPC : https://perun-aai.org/documentation/technical-documentation/rpc-api/rpc-javadoc-UsersManager.html#UsersManagergetUserExtSourceByExtLogin1

2022-02-18 11:33 UTC, xpavlic requested changes

2022-02-21 07:56 UTC, xpavlic requested changes

2022-02-21 07:56 UTC, xpavlic commented on Adapters/AdapterInterface.py
> +    ) -> str:
```suggestion
    ) -> UserExtSource:
```

2022-02-21 09:23 UTC, xpavlic approved these changes

2022-02-21 09:28 UTC, merged

2022-05-16 11:44 UTC, xpavlic commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on [GitHub release](https://github.com/CESNET/perun.connector/releases/tag/v1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2022-05-16 12:14 UTC, xpavlic commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on [GitHub release](https://github.com/CESNET/perun.connector/releases/tag/v1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: