feat: partly implemented rpc adapter
CESNET/proxyaai_perun_connection_manager pull request #3
Opened 2022-02-09 17:51 UTC by PeterBolha

implemented several methods from perun rpc adapter

2022-02-09 18:43 UTC, vyskocilpavel requested changes
I think that the ApiClient object must be pass as the param to the `*ManagerApi` (https://github.com/CESNET/proxyaai_perun_connection_manager/blob/7d06cf12f14d5579d2675b12dfd10483b1416e89/perun_openapi/api_client.py#L43) with the specified configuration(Need to be added in some configuration file with items RPC hosts, username, password, etc.) 

But maybe I don't understand how to work with the generated RPC connectors.

2022-02-11 14:31 UTC, melanger requested changes

2022-02-11 14:31 UTC, melanger commented on Adapters/PerunRpcAdapter.py
> +                name += " " + user["titleAfter"]
```suggestion
            for user_attr in ["titleBefore", "firstName", "middleName", "lastName", "titleAfter"]:
                name += user[user_attr] + " "
            name = name.strip()
```

2022-02-11 14:31 UTC, melanger commented on Adapters/PerunRpcAdapter.py
> +            )
```suggestion
        resources = [Resource(perun_attr["id"], perun_attr["vo_id"], perun_attr["facility_id"], perun_attr["name"]) for perun_attr in perun_attrs]
```
use list comprehension where possible

2022-02-11 14:31 UTC, melanger commented on Adapters/PerunRpcAdapter.py
> +        if not attr_name:
If we want defaults, I think they should be handled by AttributeUtils, not here. That will reduce similar code quite significantly.

2022-02-11 14:31 UTC, melanger commented on Adapters/PerunRpcAdapter.py
> +        unique_name = attr["value"] + ":" + group["name"]
This is repeated quite a lot, please create a local function like `get_attribute_value`, which will get the attribute and return its `["value"]` directly.

2022-02-11 14:31 UTC, melanger commented on Adapters/PerunRpcAdapter.py
> +            group["id"],
when the dictionary keys match the argument names of the constructor, you can use `Group(*group)` instead of writing individual items (this applies to all constructor calls)

2022-02-23 09:58 UTC, xpavlic requested changes

2022-02-23 09:58 UTC, xpavlic commented on Adapters/PerunRpcAdapter.py
> +            )
```suggestion
            self.CONFIG = Configuration(
                host=config_data["rpc_url"],
                username=config_data["rpc_username"],
                password=config_data["rpc_password"],
            )
```

2022-02-23 09:58 UTC, xpavlic commented on Adapters/PerunRpcAdapter.py
> +        attr = attributes_api_instance.get_attribute(group_id)
```suggestion
        attr = attributes_api_instance.get_attribute(
            group=group_id,
        )
```

2022-02-23 09:58 UTC, xpavlic commented on Adapters/PerunRpcAdapter.py
> +    ):
You also need attribute name to get attribute.

2022-02-24 14:16 UTC, xpavlic requested changes

2022-02-24 14:16 UTC, xpavlic commented on Adapters/PerunRpcAdapter.py
> +                vo.id, attr_names_map.keys()
```suggestion
                vo.id, attrNames=attr_names_map.keys()
```

2022-02-24 14:16 UTC, xpavlic commented on Adapters/PerunRpcAdapter.py
> +                facility.id, attr_name
```suggestion
                facility=facility.id, attributeName=attr_name
```

2022-02-24 14:16 UTC, xpavlic commented on config_templates/perun_rpc_config_template.yaml
> +"rpc_url": "my_url"
remove this file

2022-02-25 15:07 UTC, PeterBolha commented on Adapters/PerunRpcAdapter.py
> +                vo.id, attr_names_map.keys()
I've noticed that `get_vo_attributes` actually retrieves _all_ the attributes of given VO. I suggest we replace this call with calling `get_vo_attributes_by_names` which actually takes in a list of names to find.

2022-02-25 15:14 UTC, PeterBolha commented on Adapters/PerunRpcAdapter.py
> +                user.id, attr_names_map.keys()
Same case as in `get_vo_attributes`. I originally misunderstood the docs when writing this method. Now I'd replace it with `get_user_attributes_by_names`

2022-02-25 16:42 UTC, PeterBolha commented on Adapters/PerunRpcAdapter.py
> +    def get_sp_groups(self, rp_identifier: str) -> List[Group]:
I checked how this method is used in `simplesaml.php` and the return type is used as a `Group`. I've done a little experiment and changing the return type to `HasIdAbstract` here is going to silent the warning. However the warning will be propagated to subsequent calls of `Group` attributes other than `id` when working with the returned list of `Groups`. This problem was probably introduced when we decided to make `HasIdInterface` into `HasIdAbstract`. 

At this moment I'm not sure how to tackle this tricky type casting. I think we could drop the method `unique_entities` entirely and use `list(set(entities))` to filter out non-unique instances in a list of entities implementing custom `__hash__`  based on entity's `id`.

2022-02-25 16:44 UTC, PeterBolha commented on Adapters/PerunRpcAdapter.py
> +    ) -> List[Group]:
The same thing as I mentioned in the above suggestion regarding `get_sp_groups`

2022-02-25 17:00 UTC, PeterBolha commented on Adapters/PerunRpcAdapter.py
> +            attr_name = AttributeUtils.get_rpc_attr_name(rp_identifier_attr)
We currently have parameters `internal_attr_name` as well as `default_attr_name` in `AttributeUtils.get_rpc_attr_name`, however at the moment `rp_identifier_attr` is literally set to _"perunFacilityAttr_entityID"_ so this is the same as calling the method like this -> `get_rpc_attr_name(rp_identifier_attr, rp_identifier_attr)`.

Previously, we extracted the fallback **value** to `AttributeUtils` class, but the **key** to obtain that value is still _"perunFacilityAttr_entityID"_ in any case. I think we might want to get rid of the `default_attr_name` parameter because that's always the same according to my understanding. What we have stored in AttributeUtils.DEFAULT_ATTR_NAMES under that key is quivalent to _default attribute value_ tied to that `internal_attr_name`.

2022-02-25 17:07 UTC, PeterBolha commented on Adapters/PerunRpcAdapter.py
> +        self, rp_identifier: str, user_id: str
According to a convention we established when writing other methods I think we could _(should?)_ pass an entire `User` object as a parameter and access his/her `id` in the method body. I might be wrong though and will switch this to `int` for now.

2022-02-25 17:15 UTC, PeterBolha commented on Adapters/PerunRpcAdapter.py
> +                facility.id, attr_names_map.keys()
I think I should have used the `get_facility_attributes_by_names` method here.

2022-02-25 17:15 UTC, PeterBolha commented on Adapters/PerunRpcAdapter.py
> +                    user_ext_source.id, attr_names_map.keys()
I think I should have used the `get_user_ext_source_attributes_by_names` method here.

2022-02-25 17:24 UTC, PeterBolha commented on Adapters/PerunRpcAdapter.py
> +                user_ext_source.id, attributes
I may be misunderstanding this but upon checking the `set_user_ext_source_attributes` method in `AttributesManagerApi` I can't see where the `user_ext_source` `id` would be extracted from the kwargs dict. I don't think attributes are the problem causing this warning, rather the `id` of ext. source which is unused in the generated method in my opinion.

2022-02-25 17:29 UTC, PeterBolha commented on Adapters/PerunRpcAdapter.py
> +                    resource["id"],
I agree this is not entirely correct right now but I think it should look like this:
```
resource_capabilities = attributes_api_instance.get_attribute(
                    attribute_id=resource["id"],
                    attribute_name="urn:perun:resource:attribute-def:def:capabilities"
                )
```

2022-02-25 17:36 UTC, PeterBolha commented on Adapters/PerunRpcAdapter.py
> +                    "urn:perun:resource:attribute-def:def:capabilities",
Above reply concerns this comment as well.

2022-02-25 17:37 UTC, PeterBolha commented on Adapters/PerunRpcAdapter.py
> +                facility.id,
The same case as in resource above

2022-02-28 14:05 UTC, xpavlic commented on Adapters/PerunRpcAdapter.py
> +                    resource["id"],
The second one should be right.

2022-02-28 14:13 UTC, xpavlic commented on Adapters/PerunRpcAdapter.py
> +        self, rp_identifier: str, user_id: str
We can pass User here.

2022-02-28 14:18 UTC, xpavlic commented on Adapters/PerunRpcAdapter.py
> +                facility.id, attr_names_map.keys()
You are right.

2022-02-28 14:18 UTC, xpavlic commented on Adapters/PerunRpcAdapter.py
> +                    user_ext_source.id, attr_names_map.keys()
You are right.

2022-02-28 14:19 UTC, xpavlic commented on Adapters/PerunRpcAdapter.py
> +                user.id, attr_names_map.keys()
Right.

2022-02-28 14:19 UTC, xpavlic commented on Adapters/PerunRpcAdapter.py
> +                vo.id, attr_names_map.keys()
Right

2022-02-28 14:20 UTC, xpavlic commented on Adapters/PerunRpcAdapter.py
> +                    "urn:perun:resource:attribute-def:def:capabilities",
Same pattern as above.

2022-02-28 14:25 UTC, xpavlic commented on Adapters/PerunRpcAdapter.py
> +    def get_sp_groups(self, rp_identifier: str) -> List[Group]:
I figured out, that warning is caused by wrong imports in Model classes, which I already suggested you to fix.

2022-02-28 14:28 UTC, xpavlic requested changes
Added comments.

2022-03-01 09:36 UTC, xpavlic commented on Adapters/PerunRpcAdapter.py
> +            attr_name = AttributeUtils.get_rpc_attr_name(rp_identifier_attr)
I looked into code once more and in old implementation, you could send attribute name into function (does not have to be perunFacilityAttr_entityID) and if it is not found, then still use default value. I think, we can remove rp_identifier_attr from parameter and make it fixed value. Then we can remove default_attr_name and change AttributeUtils.

2022-03-01 11:35 UTC, xpavlic requested changes

2022-03-01 11:35 UTC, xpavlic commented on Adapters/PerunRpcAdapter.py
> +                attribute_name="urn:perun:facility:attribute-def:def"
I think this should be also read from config by AttributeUtils

2022-03-01 11:35 UTC, xpavlic commented on Adapters/PerunRpcAdapter.py
> +        self.CONFIG_FILE_PATH = "config_templates/attribute_map.yaml"
I think this is not needed.

2022-03-01 11:35 UTC, xpavlic commented on Adapters/PerunRpcAdapter.py
> +                )
I think this should cause exception, because we can not instantiate PerunRpcAdapter

2022-03-01 11:35 UTC, xpavlic commented on Adapters/PerunRpcAdapter.py
> +                f"{self.CONFIG_FILE_PATH}"
We dont need filepath, just write in config instead. And We should rethrow exception.

2022-03-03 08:10 UTC, PeterBolha commented on Adapters/PerunRpcAdapter.py
> +                )
Should we keep this log and raise, say, `ValueError` on top of that or remove the logging entirely and instead pass its error message in the exception?

2022-03-03 08:11 UTC, PeterBolha commented on Adapters/PerunRpcAdapter.py
> +                f"{self.CONFIG_FILE_PATH}"
Similar as above, should we move the entire message to the new exception or keep the logging statement as well?

2022-03-03 08:23 UTC, PeterBolha commented on Adapters/PerunRpcAdapter.py
> +            attribute_name="urn:perun:group:attribute-def:virt:voShortName",
I just noticed that this `attribute_name` is taken from `AdapterRpc` where it's used in the method `getMemberGroups` like this. However there's only `urn:perun:group:attribute-def:virt:voShortNames` defined in the config file. I'm not sure if this is a typo, but our config would return a method with return type `list` and `attribute_name` should be a single value.

2022-03-03 08:45 UTC, xpavlic commented on Adapters/PerunRpcAdapter.py
> +            attribute_name="urn:perun:group:attribute-def:virt:voShortName",
It is not a typo it is just value which is not in config. Just add it there.

2022-03-03 08:56 UTC, xpavlic commented on Adapters/PerunRpcAdapter.py
> +                )
I think propagation of exception should be enough. Also we will need manage exceptions from adapters in AdaptersManager, to be able to switch between adapters.

2022-03-03 11:16 UTC, xpavlic commented on Adapters/PerunRpcAdapter.py
> +            attribute_name="urn:perun:group:attribute-def:virt:voShortName",
I found out that in RPC you need to make group unique name from voShortName and group name, but in LDAP there is just attribute groupUniqueName. So voShortName doesnt have its equivalent in ldap and I think this is the reason, that attribute name is defined here. After this finding, I would let attribute name same as i was. (same for other cases).

2022-03-23 12:34 UTC, xpavlic requested changes
Please also remove changes in openApi. As it is automatically generated, we should not intervene manually

This should be last things to change.

2022-03-23 12:34 UTC, xpavlic commented on adapters/PerunRpcAdapter.py
> +    def _create_internal_representation_groups(self,
I think, that right type of input_groups is List[perun_openapi.model.group.Group] (model from openApi). Also add import perun_openapi.model.group to imports.

2022-03-23 12:34 UTC, xpavlic commented on adapters/PerunRpcAdapter.py
> +        groups = []
```suggestion
```

2022-03-23 12:34 UTC, xpavlic commented on adapters/PerunRpcAdapter.py
> +            return groups
```suggestion
            return []
```

2022-03-23 12:34 UTC, xpavlic commented on adapters/PerunRpcAdapter.py
> +            resources_ids = [perun_attr.id for perun_attr in perun_attrs]
```suggestion
            resources = (
                facilities_api_instance.get_assigned_resources_for_facility(
                    facility.id
                )
            )

            resources_ids = [resource.id for resource in resources]
```

2022-03-23 12:34 UTC, xpavlic commented on adapters/PerunRpcAdapter.py
> +            perun_attr = facilities_api_instance.get_facilities_by_attribute(
Rename perun_attr to facilities.

2022-03-23 12:34 UTC, xpavlic commented on adapters/PerunRpcAdapter.py
> +    #  (implement searcher in FacilityManager)
```suggestion
    #  (reimplement with Searcher, not working now)
```

2022-03-23 12:34 UTC, xpavlic commented on adapters/PerunRpcAdapter.py
> +                    attribute_name="urn:perun:resource:attribute-def:def"
get attribute_name from AttributeUtils (from config)

2022-03-23 12:34 UTC, xpavlic commented on adapters/PerunRpcAdapter.py
> +                attribute_name="urn:perun:facility:attribute-def:def"
same as above

2022-03-23 12:34 UTC, xpavlic commented on adapters/PerunRpcAdapter.py
> +            attr_names.append(default_attribute_name)
I am not sure, why you are adding loa to default attribute names.

2022-03-24 07:45 UTC, PeterBolha commented on adapters/PerunRpcAdapter.py
> +            attr_names.append(default_attribute_name)
This was a special case we discussed at one point. OpenApi's `AttributesManagerApi.get_user_attributes_by_names` returns `loa` attribute if the input is an empty array (if we don't ask for any attributes, it returns `loa` nontheless). Our implementation then pairs input attributes as keys with obtained attribute values but it arrives at an error if we recieve a value for a key we didn't ask for, therefore it isn't in the input array.

Simply put, we recieve value for an input we didn't ask for. This assignment in case of an empty input makes it explicitly ask for the default value so this implementation behaves as OpenAPI and doesn't crash with KeyError. It seems quite strange to me so perhaps I'm misunderstanding what's going on.

The same thing is happening in `get_vo_attributes`

2022-03-24 07:49 UTC, PeterBolha commented on adapters/PerunRpcAdapter.py
> +                attribute_name="urn:perun:facility:attribute-def:def"
We also discussed this on Slack if I remember correctly. We tried to extract these names to the config file but upon further inspection, we discovered that these attrs were only used by RPC adapter so we decided to revert the extraction and place them back to the rpc adapter.

2022-03-30 08:18 UTC, xpavlic requested changes

2022-03-30 08:18 UTC, xpavlic commented on adapters/PerunRpcAdapter.py
> +    # TODO add support for searching by more attributes to OpenAPI
Use Searcher instead as it is already implemented in openApi.

2022-04-13 09:45 UTC, xpavlic requested changes
Overall looks good. Squash commits please.

2022-04-14 08:10 UTC, xpavlic approved these changes

2022-04-14 08:12 UTC, merged

2022-05-16 11:44 UTC, xpavlic commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on [GitHub release](https://github.com/CESNET/perun.connector/releases/tag/v1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2022-05-16 12:13 UTC, xpavlic commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on [GitHub release](https://github.com/CESNET/perun.connector/releases/tag/v1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: