feat: LdapAdapter
CESNET/proxyaai_perun_connection_manager pull request #7
Opened 2022-02-22 00:15 UTC by Br3nKo

Implemented LdapAdapter, not sure if the exception works and/or is used correctly.

2022-04-07 08:40 UTC, PeterBolha commented on Adapters/LdapAdapter.py
>          self.ldap_base = loaded_config['base_dn']
We discussed with @xpavlic using the single underscore prefix "_" notation for "private" attributes and methods to signify that they're only used internally. Despite _variables not really being private, it could help make the code more easily understandable. I think we should apply it for LDAP attributes and methods as well.

2022-04-07 09:35 UTC, PeterBolha commented on Adapters/LdapAdapter.py
> +from Utils.ConfigStore import ConfigStore
`Utils` with capital U was an overlooked mistake. I asked Honza about it and we changed the folder name to utils. It's now in `main` so this import might not work.

2022-04-07 09:35 UTC, PeterBolha commented on Adapters/LdapAdapter.py
> +            ConfigStore.get_attribute_map()[rp_identifier_attr]['ldap']
Although this works, we have a designated method for this in `AttributeUtils`. You could create an `AttributeUtils` instance as an attribute of LdapAdapter and look for attr names using `get_ldap_attr_name` or `get_ldap_attr_names` methods. They handle a bit of the overhead and state more clearly what you're doing. This would also save you the work from the following if statement.

2022-04-07 09:35 UTC, PeterBolha commented on Adapters/LdapAdapter.py
> +    def get_users_groups_on_facility(self, rp_identifier, user_id):
We also discussed the usage of `rp_identifier` as an input parameter with Honza. In other places we use entire model instances on input when possible. That's why we changed `rp_identifier` to `Facility `as an input parameter whenever the input `rp_identifier` is only used to look up a `Facility` in the method. This is now changed in `AdapterInterface` in main. You can adjust the method inputs and test accordingly.

2022-04-07 09:35 UTC, PeterBolha commented on Adapters/LdapAdapter.py
> +    def get_facilities_by_attribute_value(self, attribute):
We should discuss with @xpavlic whether and where we use these custom exceptions. I think they might be useful but so far we haven't utilized them in any way.

2022-04-07 09:35 UTC, PeterBolha commented on Adapters/LdapAdapter.py
> +    def get_member_status_by_user_and_vo(self, user, vo):
There are more member stauses than `VALID` and `INVALID` but i think this method has no way of returning anything other than those two.

2022-04-10 15:41 UTC, xpavlic commented on Adapters/LdapAdapter.py
> +    def get_member_status_by_user_and_vo(self, user, vo):
This method can return only VALID and INVALID. More information about Member status is obtained by RPC.

2022-04-10 15:48 UTC, xpavlic commented on Adapters/LdapAdapter.py
> +    def get_facilities_by_attribute_value(self, attribute):
I would just rename this exception to AdapterSkipException. It will be caught in AdaptersManager which log and handle it.

2022-04-13 21:58 UTC, xpavlic requested changes

2022-04-13 21:58 UTC, xpavlic commented on Adapters/LdapAdapter.py
> +        self._logger.debug('Resources - ' + json.dumps(str(resources)))
I think, that str(obj) should be enough. (all occurences)
```suggestion
        self._logger.debug('Resources - ' +str(resources))

```

2022-04-13 21:58 UTC, xpavlic commented on Adapters/LdapAdapter.py
> +        )
```suggestion
        resources = self._connector.search_for_entities(
            self._ldap_base,
            '(&(objectClass=perunResource)(perunFacilityDn=perunFacilityId=' +
            facility.id + ',' + self._ldap_base + '))',
            [self.CAPABILITIES, self.ASSIGNED_GROUP_ID]
        )

```

2022-04-13 21:58 UTC, xpavlic commented on Adapters/LdapAdapter.py
> +        if user.id == '':
user.id is int not string

2022-04-13 21:58 UTC, xpavlic commented on Adapters/LdapAdapter.py
> +            ['perunResourceId', 'assignedGroupId', 'perunVoId']
```suggestion
        resources = self._connector.search_for_entities(
            self._ldap_base,
            '(&(objectClass=perunResource)(perunFacilityDn=perunFacilityId=' +
            facility.id + ',' + self._ldap_base + '))',
            ['perunResourceId', 'assignedGroupId', 'perunVoId']

```

2022-04-13 21:58 UTC, xpavlic commented on Adapters/LdapAdapter.py
> +        )
```suggestion
        return self._connector.search_for_entity(
            'perunUserId=' + str(user.id) + ',ou=People,' + self._ldap_base,
            '(objectClass=perunUser)',
            attr_names
        )

```

2022-04-13 21:58 UTC, xpavlic commented on Adapters/LdapAdapter.py
> +    def get_users_groups_on_facility(self, facility, user_id):
user_id parameter shoud be user object

2022-04-13 21:58 UTC, xpavlic commented on Adapters/LdapAdapter.py
> +        id = facility.id
```suggestion
        id = str(facility.id)

```

2022-04-13 21:58 UTC, xpavlic commented on Adapters/LdapAdapter.py
> +    def get_user_ext_source_attributes(self, user_ext_source_id, attr_names):
```suggestion
    def get_user_ext_source_attributes(self, user_ext_source, attr_names):

```

2022-04-13 21:58 UTC, xpavlic commented on Adapters/LdapAdapter.py
> +    def set_user_ext_source_attributes(self, user_ext_source_id, attr_names):
```suggestion
    def set_user_ext_source_attributes(self, user_ext_source, attr_names):

```

2022-04-13 21:58 UTC, xpavlic commented on Adapters/LdapAdapter.py
> +            attr_names
```suggestion
        return self._connector.search_for_entity(
            'perunUserId=' + str(user.id) + ',ou=People,' + self._ldap_base,
            '(objectClass=perunUser)',
            attr_names

```

2022-04-13 21:58 UTC, xpavlic commented on Adapters/LdapAdapter.py
> +            '(objectClass=perunUser)', ['perunUserId', 'memberOf'])
```suggestion
        user_with_membership = self._connector.search_for_entity(
            'perunUserId=' + str(user.id) + ',ou=People,' + self._ldap_base,
            '(objectClass=perunUser)', ['perunUserId', 'memberOf'])

```

2022-04-13 21:58 UTC, xpavlic commented on Adapters/LdapAdapter.py
> +                          'perunVoId', 'uuid', 'description']
```suggestion
        group = self._connector.search_for_entity(
            'perunVoId=' + str(vo.id) + ',' + self._ldap_base,
            '(&(objectClass=perunGroup)(perunUniqueGroupName=' +
            name + '))', ['perunGroupId', 'cn', 'perunUniqueGroupName',
                          'perunVoId', 'uuid', 'description']

```

2022-04-19 12:44 UTC, xpavlic requested changes

2022-04-19 12:44 UTC, xpavlic commented on Adapters/LdapAdapter.py
> +            return MemberStatusEnum.INVALID
Instead of returning INVALID throw exception to call another adapter. We will need to get real user status not just INVALID.

2022-04-21 20:12 UTC, merged

2022-05-16 11:43 UTC, xpavlic commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on [GitHub release](https://github.com/CESNET/perun.connector/releases/tag/v1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2022-05-16 12:13 UTC, xpavlic commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on [GitHub release](https://github.com/CESNET/perun.connector/releases/tag/v1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: